/** キャッシュキーの一覧。無効化のたびに文字列を書くのをやめ、ここへ集約する。 */
export const queryKeys = {
  setup: ["setup"] as const,
  settings: ["settings"] as const,
  aiGuard: ["aiGuard"] as const,
  autostart: ["autostart"] as const,
  home: ["home"] as const,
  maintenance: ["maintenance"] as const,
  tagOverview: ["tagOverview"] as const,
  favorites: ["favorites"] as const,
  graph: ["graph"] as const,
  connect: ["connect"] as const,
  githubAuth: ["githubAuth"] as const,
  notes: ["note"] as const,
  note: (id: string) => ["note", id] as const,
  noteFiles: (id: string) => ["noteFiles", id] as const,
  files: ["files"] as const,
  filePreview: (id: string) => ["filePreview", id] as const,
  noteCategories: ["noteCategories"] as const,
  noteLists: ["noteList"] as const,
  noteList: (category: string) => ["noteList", category] as const,
  searches: ["search"] as const,
  search: (query: string) => ["search", query] as const,
};
