// このファイルは tauri-specta の生成物です。手で編集しないこと(ADR-0002)。
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	setupState: () => typedError<SetupState, AppError>(__TAURI_INVOKE("setup_state")),
	/**  最初の vault を自動作成(既定名「わたしのノート」実体 my-notes)。 */
	onboard: () => typedError<SetupState, AppError>(__TAURI_INVOKE("onboard")),
	homeState: () => typedError<HomeState_Serialize, AppError>(__TAURI_INVOKE("home_state")),
	/**  タグ一覧(説明は KB の「タグ運用」ノート由来 — アプリは意味づけを持たない)。 */
	tagOverview: () => typedError<TagOverview, AppError>(__TAURI_INVOKE("tag_overview")),
	careDismiss: (key: string) => typedError<null, AppError>(__TAURI_INVOKE("care_dismiss", { key })),
	noteGet: (id: string) => typedError<NoteView, AppError>(__TAURI_INVOKE("note_get", { id })),
	noteSearch: (query: string) => typedError<SearchOutcome_Serialize, AppError>(__TAURI_INVOKE("note_search", { query })),
	/**  グラフビュー(FR-A7)用のノード・エッジ。退役ノートと未執筆リンク先は除く。 */
	graphData: () => typedError<GraphData, AppError>(__TAURI_INVOKE("graph_data")),
	favoritesList: () => typedError<Favorite_Serialize[], AppError>(__TAURI_INVOKE("favorites_list")),
	favoriteAdd: (fav: Favorite_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("favorite_add", { fav })),
	favoriteRemove: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("favorite_remove", { name })),
	/**  添付の追加。データは base64。 */
	attachmentAdd: (id: string, name: string, dataBase64: string) => typedError<[string, string | null], AppError>(__TAURI_INVOKE("attachment_add", { id, name, dataBase64 })),
	/**
	 *  パス指定で添付(ドラッグ&ドロップ用)。Tauri はファイルドロップを DOM に渡さず
	 *  自前イベントでパスをくれるので、Rust 側で直接読む(base64 経由より大きいファイルに強い)。
	 */
	attachmentAddFromPath: (id: string, path: string) => typedError<[string, string | null], AppError>(__TAURI_INVOKE("attachment_add_from_path", { id, path })),
	/**
	 *  クリップボードの画像を添付(ペーストのフォールバック)。
	 *  画像が無ければ Ok(None) — テキストのペーストを邪魔しない。
	 */
	attachmentPaste: (id: string) => typedError<[string, string | null] | null, AppError>(__TAURI_INVOKE("attachment_paste", { id })),
	attachmentRemove: (id: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("attachment_remove", { id, name })),
	connectState: () => typedError<ConnectState, AppError>(__TAURI_INVOKE("connect_state")),
	/**  Claude Desktop の設定にこの実行ファイルを MCP サーバーとして登録する。 */
	connectDesktop: () => typedError<null, AppError>(__TAURI_INVOKE("connect_desktop")),
	backupNow: () => typedError<string, AppError>(__TAURI_INVOKE("backup_now")),
	backupSetRemote: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("backup_set_remote", { url })),
	/**
	 *  かしこい検索をオンにする(モデル導入+全ノート埋め込み)。数分かかる。
	 * 
	 *  **同期コマンドにしてある**。Tauri は同期コマンドを別スレッドで動かすが、
	 *  async コマンドは async ランタイム上で動くため、ここのようにブロッキングで
	 *  回す処理を async にするとランタイムを止めてしまう。
	 */
	embedEnable: () => typedError<null, AppError>(__TAURI_INVOKE("embed_enable")),
	/**  現在ノートを記録して Claude Desktop を前面に(FR-A5 最小)。 */
	launchAi: (note: string | null) => typedError<null, AppError>(__TAURI_INVOKE("launch_ai", { note })),
};

/** Events */
export const events = {
	embedProgress: makeEvent<EmbedProgress>("embed-progress"),
};

/* Types */
export type AppError = 
/**  vault を開けない(未オンボーディング・レジストリの不整合)。 */
{ code: "vault_unavailable"; message: string } | 
/**  指定 ID のノートが無い(消された・まだ書かれていない)。 */
{ code: "note_not_found"; id: string } | 
/**  添付が上限を超えている。 */
{ code: "attachment_too_large"; limit_mb: number; actual_mb: number } | 
/**  Claude Desktop が見つからない(未インストール)。 */
{ code: "claude_desktop_not_found" } | 
/**  Claude Desktop を起動できなかった。 */
{ code: "claude_desktop_launch_failed" } | 
/**  バックアップ(git)の失敗。 */
{ code: "backup_failed"; message: string } | 
/**  かしこい検索の準備に失敗。 */
{ code: "embed_failed"; message: string } | 
/**  分類できないもの。message はコアが返した文言(いまは日本語)。 */
{ code: "unexpected"; message: string };

export type BackupStatus = {
	/**  origin の URL(未設定なら None = 未接続) */
	remote: string | null,
	/**  未バックアップのコミット数(remote 未設定時は全コミット数) */
	pending: number,
};

export type CareProposal = {
	key: string,
	kind: string,
	a: string,
	b: string,
	detail: string,
};

export type ConnectState = {
	desktop: DesktopStatus,
	backup: BackupStatus,
	sync_error: string | null,
	smart_search: SmartSearchState,
};

export type DesktopStatus = 
/**  Claude Desktop の設定ファイルが見つからない(未インストールか未起動) */
"not_found" | "not_connected" | "connected";

/**  かしこい検索の進み具合。数分かかるので画面へ流す。 */
export type EmbedProgress = {
	embedded: number,
	total: number,
};

/**
 *  名前付きの絞り込みセット。タグだけでなく検索語・期間・並び順も保存する
 *  (2026-08-11: 「お気に入り = 画面の絞り込み状態そのもの」に拡張)。
 *  旧形式(name/tags のみ)も読めるよう追加項目はすべて default。
 */
export type Favorite = Favorite_Serialize | Favorite_Deserialize;

/**
 *  名前付きの絞り込みセット。タグだけでなく検索語・期間・並び順も保存する
 *  (2026-08-11: 「お気に入り = 画面の絞り込み状態そのもの」に拡張)。
 *  旧形式(name/tags のみ)も読めるよう追加項目はすべて default。
 */
export type Favorite_Deserialize = {
	name: string,
	tags: string[],
	query?: string | null,
	period?: string | null,
	sort?: string | null,
};

/**
 *  名前付きの絞り込みセット。タグだけでなく検索語・期間・並び順も保存する
 *  (2026-08-11: 「お気に入り = 画面の絞り込み状態そのもの」に拡張)。
 *  旧形式(name/tags のみ)も読めるよう追加項目はすべて default。
 */
export type Favorite_Serialize = {
	name: string,
	tags: string[],
	query?: string | null,
	period?: string | null,
	sort?: string | null,
};

export type GraphData = {
	nodes: GraphNode[],
	edges: ([string, string])[],
};

export type GraphNode = {
	id: string,
	title: string,
	origin: string | null,
	status: string,
	degree: number,
};

export type Hit = Hit_Serialize | Hit_Deserialize;

export type Hit_Deserialize = {
	id: string,
	title: string | null,
	status: string,
	snippet: string,
	/**  "main"(分かち書き bm25)/ "vec"(意味検索)/ "rescue"(trigram/LIKE) */
	via: string,
	/**  意味検索のコサイン距離(関連判定は RRF でなく生距離で — 旧 KB の実測教訓) */
	distance: number | null,
	/**  所有(原則9): "human" | "agent" */
	origin: string | null,
	/**  分類タグ(空白区切りを分解済み) */
	tags: string[],
	/**  作成日時・最終更新(一覧でも見えるように) */
	created: string | null,
	updated: string | null,
};

export type Hit_Serialize = {
	id: string,
	title: string | null,
	status: string,
	snippet: string,
	/**  "main"(分かち書き bm25)/ "vec"(意味検索)/ "rescue"(trigram/LIKE) */
	via: string,
	/**  意味検索のコサイン距離(関連判定は RRF でなく生距離で — 旧 KB の実測教訓) */
	distance?: number | null,
	/**  所有(原則9): "human" | "agent" */
	origin: string | null,
	/**  分類タグ(空白区切りを分解済み) */
	tags: string[],
	/**  作成日時・最終更新(一覧でも見えるように) */
	created: string | null,
	updated: string | null,
};

export type HomeState = HomeState_Serialize | HomeState_Deserialize;

export type HomeState_Deserialize = {
	stats: Stats,
	notes: Hit_Deserialize[],
	care: CareProposal[],
	tags: ([string, number])[],
	degraded: string[],
};

export type HomeState_Serialize = {
	stats: Stats,
	notes: Hit_Serialize[],
	care: CareProposal[],
	tags: ([string, number])[],
	degraded: string[],
};

export type NoteView = {
	id: string,
	title: string,
	body: string,
	status: string,
	origin: string | null,
	tags: string[],
	created_at: string | null,
	generated_at: string | null,
	related: ([string, string | null])[],
	similar: ([string, string | null, number | null])[],
	attachments: ([string, number])[],
	vault_root: string,
};

export type SearchOutcome = SearchOutcome_Serialize | SearchOutcome_Deserialize;

export type SearchOutcome_Deserialize = {
	hits: Hit_Deserialize[],
	/**  上位ヒットから1ホップのリンク先・被リンク(id, title) */
	related: ([string, string | null])[],
	/**  劣化情報(空 = 全経路正常)。UI/クライアントに必ず見せる */
	degraded: string[],
};

export type SearchOutcome_Serialize = {
	hits: Hit_Serialize[],
	/**  上位ヒットから1ホップのリンク先・被リンク(id, title) */
	related: ([string, string | null])[],
	/**  劣化情報(空 = 全経路正常)。UI/クライアントに必ず見せる */
	degraded: string[],
};

export type SetupState = {
	needs_onboarding: boolean,
	vault_name: string | null,
	vault_path: string | null,
};

/**
 *  生成される TS では "not_installed" | "downloading" | "enabled" の union になる
 *  (JSON 表現は従来の文字列のまま)。
 */
export type SmartSearchPhase = "not_installed" | "downloading" | "enabled";

export type SmartSearchState = {
	state: SmartSearchPhase,
	embedded: number,
	total: number,
};

/**  健全性の要約(FR-A2 ホーム表示用)。 */
export type Stats = {
	total: number,
	deprecated: number,
	/**  メモ(origin: human)/ AI ノート(origin: agent)の内訳(deprecated 除く) */
	memos: number,
	agent_notes: number,
	/**  つながり(リンク)の本数 */
	links: number,
	/**  かしこい検索(段1)が導入済みか */
	embed_enabled: boolean,
	/**  現行スタンプで埋め込み済みのノート数(欠損の可視化 — 沈黙停止の教訓) */
	embedded: number,
};

/**
 *  タグの一覧(使用数+説明)。**説明はアプリが持たず KB の「タグ運用」ノートから読む**
 *  (タグの意味づけは AI とユーザーの会話で決まる — 2026-08-10 方針)。
 *  表(| タグ | 説明 |)と箇条書き(- タグ — 説明 / - タグ: 説明)の両方を拾う。
 */
export type TagInfo = {
	tag: string,
	count: number,
	description: string | null,
};

export type TagOverview = {
	tags: TagInfo[],
	glossary_note: string | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

