// このファイルは tauri-specta の生成物です。手で編集しないこと(ADR-0002)。
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	setupState: () => typedError<SetupState, AppError>(__TAURI_INVOKE("setup_state")),
	/**  最初の vault を自動作成(既定名「わたしのノート」実体 my-notes)。 */
	onboard: () => typedError<SetupState, AppError>(__TAURI_INVOKE("onboard")),
	/**
	 *  2台目以降: private GitHub repository にある既存 Vault を検査・復元して登録する。
	 *  復元先は未使用 path を選び、既存フォルダへ overlay しない。
	 */
	onboardExisting: (url: string) => typedError<SetupState, AppError>(__TAURI_INVOKE("onboard_existing", { url })),
	settingsGet: () => typedError<Settings, AppError>(__TAURI_INVOKE("settings_get")),
	settingsSetAiKbEnabled: (enabled: boolean) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_set_ai_kb_enabled", { enabled })),
	settingsSetClaudeKbEnabled: (enabled: boolean) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_set_claude_kb_enabled", { enabled })),
	settingsSetGptKbEnabled: (enabled: boolean) => typedError<Settings, AppError>(__TAURI_INVOKE("settings_set_gpt_kb_enabled", { enabled })),
	homeState: () => typedError<HomeState_Serialize, AppError>(__TAURI_INVOKE("home_state")),
	/**  タグ一覧(説明は KB の「タグ運用」ノート由来 — アプリは意味づけを持たない)。 */
	tagOverview: () => typedError<TagOverview, AppError>(__TAURI_INVOKE("tag_overview")),
	careDismiss: (key: string) => typedError<null, AppError>(__TAURI_INVOKE("care_dismiss", { key })),
	noteGet: (id: string) => typedError<NoteView, AppError>(__TAURI_INVOKE("note_get", { id })),
	noteSearch: (query: string) => typedError<SearchOutcome_Serialize, AppError>(__TAURI_INVOKE("note_search", { query })),
	noteCategories: () => typedError<NoteCategories, AppError>(__TAURI_INVOKE("note_categories")),
	/**  選択ディレクトリ配下のノートをcursor pageで返す。 */
	noteList: (category: string, after: string | null, limit: number) => typedError<NoteListPage, AppError>(__TAURI_INVOKE("note_list", { category, after, limit })),
	/**  グラフビュー(FR-A7)用のノード・エッジ。退役ノートと未執筆リンク先は除く。 */
	graphData: () => typedError<GraphData, AppError>(__TAURI_INVOKE("graph_data")),
	favoritesList: () => typedError<Favorite_Serialize[], AppError>(__TAURI_INVOKE("favorites_list")),
	favoriteAdd: (fav: Favorite_Deserialize) => typedError<null, AppError>(__TAURI_INVOKE("favorite_add", { fav })),
	favoriteRemove: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("favorite_remove", { name })),
	/**  そのノートのファイル(最新版だけ)と、まだ移行していない旧添付。 */
	noteFiles: (id: string) => typedError<NoteFiles, AppError>(__TAURI_INVOKE("note_files", { id })),
	/**
	 *  パスから取り込む(選択・ドラッグ&ドロップ)。
	 * 
	 *  `supersedes` を渡すと**新しい版**になる(前の版は残る)。
	 */
	fileAdd: (noteId: string, path: string, supersedes: string | null) => typedError<Added, AppError>(__TAURI_INVOKE("file_add", { noteId, path, supersedes })),
	/**
	 *  クリップボードの画像を取り込む。画像が無ければ `None`(テキストの貼り付けを邪魔しない)。
	 * 
	 *  WKWebView は DOM の paste にクリップボード画像を渡さないため、この経路が要る。
	 */
	fileAddFromClipboard: (noteId: string) => typedError<{
	file: FileRow,
	/**  大きいという警告(拒否ではない)。閾値をバイトで返す */
	warn_over_bytes: number | null,
	/**  仕事のリポジトリ内なので同期しない設定に固定した。画面はこの理由を出す */
	forced_local_only: boolean,
	/**  Full Artifact の remote 到達状態。失敗の詳細は同期状態に集約する。 */
	delivery: DeliveryStatus,
} | null, AppError>(__TAURI_INVOKE("file_add_from_clipboard", { noteId })),
	/**  このノートから外す。**実体は消えない**(GC を持たない MVP で「削除」と言わない)。 */
	fileDetach: (noteId: string, id: string, expectedVersion: number) => typedError<null, AppError>(__TAURI_INVOKE("file_detach", { noteId, id, expectedVersion })),
	/**  手元に無い実体を取り寄せる。戻り値は取り寄せた後の状態(都度算出)。 */
	fileFetch: (id: string) => typedError<Availability, AppError>(__TAURI_INVOKE("file_fetch", { id })),
	/**
	 *  開く。**中身は必ず resolver 経由で取り出す。**
	 * 
	 *  OS のアプリへ渡すにはパスが要るが、置き場のファイル名は照合値(hash)なので、
	 *  表示名を付けた複製を一時領域に作ってから渡す。内容は不変なので使い回せる。
	 * 
	 *  経路をここに一本化しているのは、**画面へパスを渡さない**ため。パスを渡すと
	 *  「手元に無いものの中身を開かない」が画面側の作法に落ちる(決定9・resolver の doc)。
	 */
	fileOpen: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("file_open", { id })),
	/**  移行前の添付を開く。台帳が無いので保管庫の中の実ファイルを直接指す(決定4)。 */
	legacyOpen: (noteId: string, name: string) => typedError<null, AppError>(__TAURI_INVOKE("legacy_open", { noteId, name })),
	connectState: () => typedError<ConnectState, AppError>(__TAURI_INVOKE("connect_state")),
	/**  Vault の有無に依存しないため、初回の「既存 Vault を復元」画面からも呼べる。 */
	githubAuthState: () => typedError<GitHubAuthState, AppError>(__TAURI_INVOKE("github_auth_state")),
	/**  OAuth device flow は polling を含む blocking 処理なので同期 command にする。 */
	githubSignIn: () => typedError<GitHubAuthState, AppError>(__TAURI_INVOKE("github_sign_in")),
	githubSignOut: () => typedError<null, AppError>(__TAURI_INVOKE("github_sign_out")),
	/**  Webview に任意 URL を開く権限を渡さず、GitHub の固定ページだけを OS へ渡す。 */
	githubOpenDevicePage: () => typedError<null, AppError>(__TAURI_INVOKE("github_open_device_page")),
	/**  Claude Desktop の設定にこの実行ファイルを MCP サーバーとして登録する。 */
	connectDesktop: () => typedError<null, AppError>(__TAURI_INVOKE("connect_desktop")),
	backupNow: () => typedError<string, AppError>(__TAURI_INVOKE("backup_now")),
	backupCreateRepository: (name: string) => typedError<null, AppError>(__TAURI_INVOKE("backup_create_repository", { name })),
	backupSetRemote: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("backup_set_remote", { url })),
	/**
	 *  かしこい検索をオンにする(モデル導入+全ノート埋め込み)。数分かかる。
	 * 
	 *  **同期コマンドにしてある**。Tauri は同期コマンドを別スレッドで動かすが、
	 *  async コマンドは async ランタイム上で動くため、ここのようにブロッキングで
	 *  回す処理を async にするとランタイムを止めてしまう。
	 */
	embedEnable: () => typedError<null, AppError>(__TAURI_INVOKE("embed_enable")),
	/**  現在ノートを記録して Claude Desktop を前面に(FR-A5 最小)。 */
	launchAi: (note: string | null) => typedError<null, AppError>(__TAURI_INVOKE("launch_ai", { note })),
};

/** Events */
export const events = {
	embedProgress: makeEvent<EmbedProgress>("embed-progress"),
	gitHubDeviceAuthorization: makeEvent<GitHubDeviceAuthorization>("git-hub-device-authorization"),
	vaultRestoreProgress: makeEvent<VaultRestoreProgress>("vault-restore-progress"),
};

/* Types */
/**  取り込んだ結果。警告と「区分を固定した」は拒否ではないので、行と一緒に返す。 */
export type Added = {
	file: FileRow,
	/**  大きいという警告(拒否ではない)。閾値をバイトで返す */
	warn_over_bytes: number | null,
	/**  仕事のリポジトリ内なので同期しない設定に固定した。画面はこの理由を出す */
	forced_local_only: boolean,
	/**  Full Artifact の remote 到達状態。失敗の詳細は同期状態に集約する。 */
	delivery: DeliveryStatus,
};

export type AppError = 
/**  vault を開けない(未オンボーディング・レジストリの不整合)。 */
{ code: "vault_unavailable" } | 
/**  指定 ID のノートが無い(消された・まだ書かれていない)。 */
{ code: "note_not_found"; id: string } | 
/**  「本体も同期」の上限を超えている。quota 不足とは別物(ADR-0003 決定8)。 */
{ code: "file_too_large"; size: number; limit: number } | 
/**  別の場所で更新された。**自動再試行も強制上書きもしない**(決定7)。 */
{ code: "file_conflict"; expected: number; current: number } | 
/**  端末固有の場所は指せない(他の端末から辿れないため)。 */
{ code: "file_location_unstable" } | 
/**  仕事のリポジトリ由来なので、この変更は認めない。 */
{ code: "file_client_repo_locked" } | 
/**  持ち出しを広げる変更なので、確認を経ていない限り通さない(決定10)。 */
{ code: "file_needs_confirm" } | 
/**  識別子・参照名の形が不正。 */
{ code: "file_malformed"; field: string } | 
/**  手元に無い(または方針で閉じている)ので開けない。 */
{ code: "file_not_here" } | 
/**
 *  クリップボード画像が大きすぎる。**ファイルの上限ではない** —
 *  この経路だけ streaming できず全量がメモリに載るため(決定8)。
 */
{ code: "clipboard_image_too_large" } | 
/**  Claude Desktop が見つからない(未インストール)。 */
{ code: "claude_desktop_not_found" } | 
/**  Claude Desktop を起動できなかった。 */
{ code: "claude_desktop_launch_failed" } | 
/**  バックアップ・復元の失敗。既知の理由は画面が翻訳して次の行動を案内する。 */
{ code: "backup_failed"; kind: BackupFailureKind | null } | 
/**  かしこい検索の準備に失敗。 */
{ code: "embed_failed" } | 
/**  コアの失敗。診断詳細は画面へ運ばず、kindだけを翻訳する。 */
{ code: "core_failed"; kind: CoreErrorKind } | 
/**  Tauri / OS 層で分類できないもの。画面はmessageを表示せずログだけに使う。 */
{ code: "unexpected"; message: string };

/**  この端末で実体を開けるか。**台帳には載せない**(上の doc 参照)。 */
export type Availability = 
/**  手元にある */
"local" | 
/**  この端末には無い(取り寄せられる可能性がある) */
"missing" | 
/**  方針により、この端末では開かない。**取得の再試行も提案しない** */
"unavailable_by_policy";

export type BackupFailureKind = "authentication" | "permission" | "privacy_check" | "network" | "invalid_repository" | "remote_missing" | "quota" | "lfs_unavailable" | "remote_object_missing" | "integrity_mismatch" | "invalid_vault" | "workspace_mismatch" | "destination_exists" | "commit" | "lfs_upload" | "git_push" | "git_pull" | "git_conflict";

export type BackupStatus = {
	/**  origin の URL(未設定なら None = 未接続) */
	remote: string | null,
	/**  未バックアップのコミット数(remote 未設定時は全コミット数) */
	pending: number,
};

export type CareProposal = {
	key: string,
	kind: string,
	a: string,
	b: string,
	detail: string,
};

export type ConnectState = {
	desktop: DesktopStatus,
	backup: BackupStatus,
	sync_error: string | null,
	sync_error_kind: BackupFailureKind | null,
	smart_search: SmartSearchState,
};

/**  画面が次の行動を訳し分けるための安定した分類。 */
export type CoreErrorKind = "vault_unavailable" | "invalid_input" | "storage" | "index" | "configuration" | "embedding" | "unexpected";

/**  データ本体を返し続けられる部分失敗。 */
export type Degradation = { code: "remote_sync"; detail: string } | { code: "index_sync"; detail: string } | { code: "index_metadata"; note: string; detail: string } | { code: "index_read"; note: string; detail: string } | { code: "index_parse"; note: string; detail: string } | { code: "embedding_index_pending"; remaining: number } | { code: "embedding_index"; detail: string } | { code: "main_search"; detail: string } | { code: "semantic_search"; detail: string } | { code: "rescue_search"; detail: string } | { code: "related_notes"; detail: string } | { code: "similar_notes"; detail: string } | { code: "current_note_context"; detail: string } | { code: "care_detection"; detail: string } | { code: "care_list"; detail: string } | { code: "tag_counts"; detail: string } | { code: "graph_nodes"; detail: string } | { code: "graph_edges"; detail: string };

export type DeliveryStatus = 
/**  `local_only` なので送信対象ではない。 */
"local_only" | 
/**  `full` だがバックアップ先がまだ無い。 */
"remote_not_configured" | 
/**  LFS object と Git ref の双方が remote へ到達した。 */
"confirmed" | 
/**  ローカル取り込みは成功したが commit / privacy gate / upload のいずれかが失敗した。 */
"degraded";

export type DesktopStatus = 
/**  Claude Desktop の設定ファイルが見つからない(未インストールか未起動) */
"not_found" | "not_connected" | "connected";

/**  かしこい検索の進み具合。数分かかるので画面へ流す。 */
export type EmbedProgress = {
	embedded: number,
	total: number,
};

/**
 *  名前付きの絞り込みセット。タグだけでなく検索語・期間・並び順も保存する
 *  (2026-08-11: 「お気に入り = 画面の絞り込み状態そのもの」に拡張)。
 *  旧形式(name/tags のみ)も読めるよう追加項目はすべて default。
 */
export type Favorite = Favorite_Serialize | Favorite_Deserialize;

/**
 *  名前付きの絞り込みセット。タグだけでなく検索語・期間・並び順も保存する
 *  (2026-08-11: 「お気に入り = 画面の絞り込み状態そのもの」に拡張)。
 *  旧形式(name/tags のみ)も読めるよう追加項目はすべて default。
 */
export type Favorite_Deserialize = {
	name: string,
	tags: string[],
	query?: string | null,
	period?: string | null,
	sort?: string | null,
};

/**
 *  名前付きの絞り込みセット。タグだけでなく検索語・期間・並び順も保存する
 *  (2026-08-11: 「お気に入り = 画面の絞り込み状態そのもの」に拡張)。
 *  旧形式(name/tags のみ)も読めるよう追加項目はすべて default。
 */
export type Favorite_Serialize = {
	name: string,
	tags: string[],
	query?: string | null,
	period?: string | null,
	sort?: string | null,
};

/**
 *  画面が1行を描くのに要る分だけ。台帳をそのまま渡すと、画面が内部の語を
 *  知ることになる(正本「内部語を見せない語彙」)。
 */
export type FileRow = {
	id: string,
	/**  更新に必要(競合を検出するため画面が持ち回る) */
	version: number,
	name: string,
	size: number,
	media_type: string,
	/**  この端末で開けるか。**同期される値ではなく、都度算出する**(決定9) */
	availability: Availability,
	sensitivity: Sensitivity,
	sync: SyncPolicy,
	/**  元の場所を指しているだけ(この保管庫は複製を持っていない) */
	linked: boolean,
	client_repo: boolean,
	/**  取り寄せを提案してよいか。**方針で閉じているものには提案しない** */
	can_fetch: boolean,
	added_at: string,
};

export type GitHubAuthState = {
	/**  OAuth App の client ID が build または実行環境に設定済みか。 */
	configured: boolean,
	/**  OS keychain に利用可能な credential があるか。 */
	signed_in: boolean,
	account_login: string | null,
};

/**  GitHub device flow で画面へ出してよい情報。device code / token は含めない。 */
export type GitHubDeviceAuthorization = {
	user_code: string,
	verification_uri: string,
	expires_in: number,
};

export type GraphData = {
	nodes: GraphNode[],
	edges: ([string, string])[],
	degraded: Degradation[],
};

export type GraphNode = {
	id: string,
	title: string,
	origin: string | null,
	status: string,
	degree: number,
};

export type Hit = Hit_Serialize | Hit_Deserialize;

export type Hit_Deserialize = {
	id: string,
	title: string | null,
	status: string,
	snippet: string,
	/**  "main"(分かち書き bm25)/ "vec"(意味検索)/ "rescue"(trigram/LIKE) */
	via: string,
	/**  意味検索のコサイン距離(関連判定は RRF でなく生距離で — 旧 KB の実測教訓) */
	distance: number | null,
	/**  所有(原則9): "human" | "agent" */
	origin: string | null,
	/**  分類タグ(空白区切りを分解済み) */
	tags: string[],
	/**  作成日時・最終更新(一覧でも見えるように) */
	created: string | null,
	updated: string | null,
};

export type Hit_Serialize = {
	id: string,
	title: string | null,
	status: string,
	snippet: string,
	/**  "main"(分かち書き bm25)/ "vec"(意味検索)/ "rescue"(trigram/LIKE) */
	via: string,
	/**  意味検索のコサイン距離(関連判定は RRF でなく生距離で — 旧 KB の実測教訓) */
	distance?: number | null,
	/**  所有(原則9): "human" | "agent" */
	origin: string | null,
	/**  分類タグ(空白区切りを分解済み) */
	tags: string[],
	/**  作成日時・最終更新(一覧でも見えるように) */
	created: string | null,
	updated: string | null,
};

export type HomeState = HomeState_Serialize | HomeState_Deserialize;

export type HomeState_Deserialize = {
	stats: Stats,
	notes: Hit_Deserialize[],
	care: CareProposal[],
	tags: ([string, number])[],
	degraded: Degradation[],
};

export type HomeState_Serialize = {
	stats: Stats,
	notes: Hit_Serialize[],
	care: CareProposal[],
	tags: ([string, number])[],
	degraded: Degradation[],
};

/**  移行前の添付(`<id>.files/`)。読み取り専用の旧経路(決定4)。 */
export type LegacyFile = {
	name: string,
	size: number,
};

/**  サイドバー用のディレクトリと子孫ノート件数。ノート本文は返さない。 */
export type NoteCategories = {
	categories: NoteCategory[],
	degraded: Degradation[],
};

/**  サイドバーに出すディレクトリ。count は直下だけでなく子孫ノートを含む。 */
export type NoteCategory = {
	path: string,
	name: string,
	count: number,
};

export type NoteFiles = {
	files: FileRow[],
	/**  まだ台帳に載っていない旧添付。移行までは並べて見せるだけにする */
	legacy: LegacyFile[],
};

/**  ID順のcursor page。全ノートを一度に画面へ渡さない。 */
export type NoteListPage = {
	notes: NoteSummary[],
	total: number,
	next_cursor: string | null,
	degraded: Degradation[],
};

/**  カテゴリ別一覧の1行。本文全体を画面へ運ばないための軽量表現。 */
export type NoteSummary = {
	id: string,
	title: string | null,
	description: string,
	tags: string[],
	created: string | null,
	updated: string | null,
	/**  リンク先と被リンクを合わせた、現存するノートの件数。 */
	linked_count: number,
	/**  現行の埋め込みがなければ None。あれば、未リンクの近いノートがあるか。 */
	has_similar: boolean | null,
	/**  台帳ファイルと旧添付の合計。ファイルシステム由来なので呼び出し層で補う。 */
	file_count: number,
};

export type NoteView = {
	id: string,
	title: string,
	description: string | null,
	body: string,
	status: string,
	origin: string | null,
	tags: string[],
	created_at: string | null,
	generated_at: string | null,
	related: ([string, string | null])[],
	similar: ([string, string | null, number | null])[],
	degraded: Degradation[],
	vault_root: string,
};

export type RestorePhase = "checking" | "cloning" | "restoring_files" | "finalizing";

export type SearchOutcome = SearchOutcome_Serialize | SearchOutcome_Deserialize;

export type SearchOutcome_Deserialize = {
	hits: Hit_Deserialize[],
	/**  上位ヒットから1ホップのリンク先・被リンク(id, title) */
	related: ([string, string | null])[],
	/**  劣化情報(空 = 全経路正常)。UI/クライアントに必ず見せる */
	degraded: Degradation[],
};

export type SearchOutcome_Serialize = {
	hits: Hit_Serialize[],
	/**  上位ヒットから1ホップのリンク先・被リンク(id, title) */
	related: ([string, string | null])[],
	/**  劣化情報(空 = 全経路正常)。UI/クライアントに必ず見せる */
	degraded: Degradation[],
};

/**
 *  閲覧区分。**転送軸(`SyncPolicy`)とは別の軸**で、UI でも1語に統合しない
 *  (統合すると、正本が分けた軸を画面で混ぜ直すことになる)。
 */
export type Sensitivity = "private" | "shared";

export type Settings = {
	ai_kb_enabled?: boolean,
	claude_kb_enabled?: boolean,
	gpt_kb_enabled?: boolean,
};

export type SetupState = {
	needs_onboarding: boolean,
	vault_name: string | null,
	vault_path: string | null,
};

/**
 *  生成される TS では "not_installed" | "downloading" | "enabled" の union になる
 *  (JSON 表現は従来の文字列のまま)。
 */
export type SmartSearchPhase = "not_installed" | "downloading" | "enabled";

export type SmartSearchState = {
	state: SmartSearchPhase,
	embedded: number,
	total: number,
};

/**  健全性の要約(FR-A2 ホーム表示用)。 */
export type Stats = {
	total: number,
	deprecated: number,
	/**  メモ(origin: human)/ AI ノート(origin: agent)の内訳(deprecated 除く) */
	memos: number,
	agent_notes: number,
	/**  つながり(リンク)の本数 */
	links: number,
	/**  かしこい検索(段1)が導入済みか */
	embed_enabled: boolean,
	/**  現行スタンプで埋め込み済みのノート数(欠損の可視化 — 沈黙停止の教訓) */
	embedded: number,
};

/**  転送軸。どこまで端末の外へ出すか。並び順がそのまま「広さ」になる。 */
export type SyncPolicy = 
/**  この端末だけ。台帳も外へ出さない */
"local_only" | 
/**  実体も同期する */
"full";

/**
 *  タグの一覧(使用数+説明)。**説明はアプリが持たず KB の「タグ運用」ノートから読む**
 *  (タグの意味づけは AI とユーザーの会話で決まる — 2026-08-10 方針)。
 *  表(| タグ | 説明 |)と箇条書き(- タグ — 説明 / - タグ: 説明)の両方を拾う。
 */
export type TagInfo = {
	tag: string,
	count: number,
	description: string | null,
};

export type TagOverview = {
	tags: TagInfo[],
	glossary_note: string | null,
	degraded: Degradation[],
};

/**  既存Vaultの検査・clone・Full Artifact復元の進捗。 */
export type VaultRestoreProgress = {
	phase: RestorePhase,
	completed: number,
	total: number,
	fetched: number,
	reused: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

