import { tv } from "tailwind-variants";

export const noteCountTrendVariants = tv({
  slots: {
    section: "mt-7 min-w-0",
    header: "mb-3 flex flex-wrap items-center justify-between gap-2",
    heading: "text-muted text-xl font-medium tracking-[0.04em]",
    refreshIcon: "size-3.5",
    card: "border-line bg-panel min-w-0 rounded-xl border p-4",
    status: "text-muted text-sm",
    period: "text-muted mb-3 text-xs",
    figure: "mt-4",
    caption: "mb-4 flex flex-wrap items-baseline gap-x-3 gap-y-1",
    latestLabel: "text-muted text-xs",
    latestValue: "text-ink text-2xl font-semibold tabular-nums",
    latestDate: "text-muted text-xs tabular-nums",
    chart: "grid min-w-0 grid-cols-[auto_minmax(0,1fr)] gap-x-2",
    scale: "text-muted flex h-36 flex-col justify-between text-[10px] tabular-nums",
    plot: "relative h-36 min-w-0",
    drawing: "border-line absolute inset-x-1 inset-y-1 border-b",
    svg: "absolute size-full overflow-visible",
    line: "stroke-grow fill-none",
    point: "bg-grow absolute -mt-1 -ml-1 size-2 rounded-full",
    axis: "text-muted mt-1.5 flex justify-between gap-2 text-[10px] tabular-nums",
    help: "text-muted mt-3 text-[11px] leading-relaxed",
    details: "border-line mt-4 border-t pt-3",
    summary: "text-muted cursor-pointer text-xs",
    tableWrap: "mt-2 overflow-x-auto",
    table: "w-full text-left text-xs",
    tableHead: "text-muted",
    dateColumn: "py-1 pr-3 font-normal whitespace-nowrap",
    countColumn: "py-1 pl-3 text-right font-normal",
    tableBody: "text-ink tabular-nums",
  },
  variants: {
    unavailable: { true: { status: "text-danger" } },
  },
});
